# Site settings
title: Yunis
description: 潜心修行。。
email: p332963965@qq.com
baseurl: /swift
url: "http://pranav.maangalabs.com" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
feedburner_username: Yunis
#twitter
twitter_username: pranavrajs
github_username:  pranavrajs

#linkedin
linkedin_username: pranavrajs

#google analytics


#fb_username
fb_username: pranav.tayberrycreative

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: maangalabscom
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  pranavrajs:
    display_name: Pranav Raj S
    email: 332963965@qq.com
    fb: 
    linkedin: 
    twitter: 
    github: 
